database.yml
development:
 adapter: postgresql
 encoding: unicode
 database: datestar_development
 pool: 5
 host: localhost
 username: postgres
 password:

production:
 adapter: postgresql
 encoding: unicode
 database: datestar_production
 pool: 5
 host: localhost
 username: postgres
 password: 