development:
  adapter: postgresql
  encoding: unicode
  database: datestar_development
  pool: 5
  host: localhost
  username: postgres
<<<<<<< HEAD
  password: 123
=======
  password: Akarnani1
>>>>>>> 9c51614bb9580447f77b13bc43a09a710a88b6fc

production:
  adapter: postgresql
  encoding: unicode
  database: datestar_production
  pool: 5
  host: localhost
  username: postgres
<<<<<<< HEAD
  password: 123
=======
  password: Akarnani1
>>>>>>> 9c51614bb9580447f77b13bc43a09a710a88b6fc
