development:
  adapter: postgresql
  encoding: unicode
  database: datestar_development
  pool: 5
  host: localhost
  username: postgres
  password: 123

production:
  adapter: postgresql
  encoding: unicode
  database: datestar_production
  pool: 5
  host: localhost
  username: postgres
  password: 123